version: '3.7'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: MYSQL_DB 
            MYSQL_USER: xsun
            MYSQL_PASSWORD: xsun
